### PR TITLE
Adds a partial function macro `@$`

### PR DESCRIPTION
**Pull request by avik-pal**
This allows us to create Partial Functions where arguments at arbitrary indices are missing.

### CODE REVIEW

**Comment by archermarx** [comment]
Neat idea, and thanks for the PR! Could you provide an example of usage?

**Comment by archermarx** [comment]
Nvm, I just looked through and saw your documentation. I think this looks great!

**Comment by archermarx** [comment]
This looks cool! Give me a day or two to look through this in detail. I'm out of town and away from my computer currently.

**Review by archermarx — COMMENTED** [review]
This looks good! My one thought: would it be possible to merge the GeneralizedPartialFunction struct with the base PartialFunction struct? That way we can reduce some code duplication

**Comment by avik-pal** [comment]
Let me go through the implementation and try that. I agree it will reduce code duplication.

**Review by archermarx — COMMENTED** [review]
Looks good! I'm currently in the middle of fixing some of the CI on this repo. Once that is fixed, I'll try and run CI on this branch

**Comment by archermarx** [comment]
@JuliaRegistrator register

**Pull request merged**
